### ISSUE TITLE
Trunk LuCI firewall page does not load

### ISSUE THREAD

**Issue by gwlim** [openwrt/luci#2846]
To reproduce
-Install openwrt trunk with luci
-Go to firewall page

```
this.ifname.charAt is not a function
  at getType (http://192.168.1.7/luci-static/resources/network.js:248:585)
  at deviceSort (http://192.168.1.7/luci-static/resources/network.js:97:114)
  at getDevices (http://192.168.1.7/luci-static/resources/network.js:239:4)
  at renderZone (http://192.168.1.7/luci-static/resources/tools/widgets.js:12:172)
  at renderWidget (http://192.168.1.7/luci-static/resources/tools/widgets.js:20:178)
```
I checked zone.js, is it wise to use offload to decide whether to render the page?

**Comment by jow-** [comment]
Canont reproduce it here on a clean build. Please provide the following command outputs:

```
ubus call network.wireless status
ubus call luci netdevs
ubus call luci ifaddrs
ubus call luci boardjson
ubus call network.interface dump
ubus call network.device status
```

**Comment by gwlim** [comment]
It is a standard firefox.
The only other non-standard thing I did was I selected 
LUCI_SRCDIET=y
I cloned from trunk, ./scripts/feeds update -a && ./scripts/feeds install -a
Then select TP-Link WR1043NDv1 and LuCI metapackage.
That is all

**Comment by jow-** [comment]
I need the output of the ubus commands above to figure out the root cause. You can also send them via mail to me if you prefer that.

**Comment by gwlim** [comment]
```
{
	"radio0": {
		"up": false,
		"pending": false,
		"autostart": true,
		"disabled": false,
		"retry_setup_failed": true,
		"config": {
			"channel": "11",
			"hwmode": "11g",
			"path": "platform/ath9k",
			"htmode": "HT20"
		},
		"interfaces": [
			
		]
	},
	"radio1": {
		"up": true,
		"pending": false,
		"autostart": true,
		"disabled": false,
		"retry_setup_failed": false,
		"config": {
			"channel": "11",
			"hwmode": "11g",
			"path": "platform/ahb/180c0000.wmac",
			"htmode": "HT20"
		},
		"interfaces": [
			
		]
	}
}
{
	"eth0.2": {
		"mac": "Removed",
		"type": 1,
		"name": "eth0.2",
		"up": true,
		"mtu": 1500,
		"qlen": 1000
	},
	"lo": {
		"mac": "00:00:00:00:00:00",
		"type": 772,
		"name": "lo",
		"up": true,
		"mtu": 65536,
		"qlen": 1000
	},
	"br-lan": {
		"mac": "Removed",
		"type": 1,
		"stp": false,
		"up": true,
		"ports": [
			"eth0.1"
		],
		"bridge": true,
		"name": "br-lan",
		"id": "Removed",
		"mtu": 1500,
		"qlen": 1000
	},
	"eth0": {
		"mac": "Removed",
		"type": 1,
		"name": "eth0",
		"up": true,
		"mtu": 1500,
		"qlen": 1000
	},
	"eth0.1": {
		"mac": "Removed",
		"type": 1,
		"name": "eth0.1",
		"up": true,
		"master": "br-lan",
		"mtu": 1500,
		"qlen": 1000
	}
}
{
	"result": [
		{
			"data": {
				"rx_bytes": 9952,
				"tx_bytes": 9952,
				"tx_errors": 0,
				"rx_errors": 0,
				"tx_packets": 141,
				"rx_packets": 141,
				"multicast": 0,
				"collisions": 0,
				"rx_dropped": 0,
				"tx_dropped": 0
			},
			"flags": {
				"broadcast": false,
				"promisc": false,
				"up": true,
				"loopback": true,
				"noarp": false,
				"multicast": false,
				"pointtopoint": false
			},
			"addr": "00:00:00:00:00:00",
			"name": "lo",
			"dstaddr": "00:00:00:00:00:00",
			"family": "packet",
			"hatype": 772,
			"broadaddr": "00:00:00:00:00:00",
			"ifindex": 1
		},
		{
			"data": {
				"rx_bytes": 131413,
				"tx_bytes": 106966,
				"tx_errors": 0,
				"rx_errors": 0,
				"tx_packets": 990,
				"rx_packets": 1262,
				"multicast": 0,
				"collisions": 0,
				"rx_dropped": 4,
				"tx_dropped": 0
			},
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": "Removed",
			"name": "eth0",
			"dstaddr": "ff:ff:ff:ff:ff:ff",
			"family": "packet",
			"hatype": 1,
			"broadaddr": "ff:ff:ff:ff:ff:ff",
			"ifindex": 2
		},
		{
			"data": {
				"rx_bytes": 87222,
				"tx_bytes": 89202,
				"tx_errors": 0,
				"rx_errors": 0,
				"tx_packets": 870,
				"rx_packets": 1021,
				"multicast": 0,
				"collisions": 0,
				"rx_dropped": 0,
				"tx_dropped": 0
			},
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": "Removed",
			"name": "br-lan",
			"dstaddr": "ff:ff:ff:ff:ff:ff",
			"family": "packet",
			"hatype": 1,
			"broadaddr": "ff:ff:ff:ff:ff:ff",
			"ifindex": 5
		},
		{
			"data": {
				"rx_bytes": 87406,
				"tx_bytes": 89202,
				"tx_errors": 0,
				"rx_errors": 0,
				"tx_packets": 870,
				"rx_packets": 1025,
				"multicast": 100,
				"collisions": 0,
				"rx_dropped": 4,
				"tx_dropped": 0
			},
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": "Removed",
			"name": "eth0.1",
			"dstaddr": "ff:ff:ff:ff:ff:ff",
			"family": "packet",
			"hatype": 1,
			"broadaddr": "ff:ff:ff:ff:ff:ff",
			"ifindex": 6
		},
		{
			"data": {
				"rx_bytes": 15415,
				"tx_bytes": 12002,
				"tx_errors": 0,
				"rx_errors": 0,
				"tx_packets": 101,
				"rx_packets": 156,
				"multicast": 18,
				"collisions": 0,
				"rx_dropped": 0,
				"tx_dropped": 0
			},
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": "Removed",
			"name": "eth0.2",
			"dstaddr": "ff:ff:ff:ff:ff:ff",
			"family": "packet",
			"hatype": 1,
			"broadaddr": "ff:ff:ff:ff:ff:ff",
			"ifindex": 7
		},
		{
			"netmask": "255.0.0.0",
			"data": [
				
			],
			"flags": {
				"broadcast": false,
				"promisc": false,
				"up": true,
				"loopback": true,
				"noarp": false,
				"multicast": false,
				"pointtopoint": false
			},
			"addr": "127.0.0.1",
			"prefix": 8,
			"family": "inet",
			"dstaddr": "127.0.0.1",
			"broadaddr": "127.0.0.1",
			"name": "lo"
		},
		{
			"netmask": "255.255.255.0",
			"data": [
				
			],
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": "192.168.1.7",
			"prefix": 24,
			"family": "inet",
			"dstaddr": "192.168.1.255",
			"broadaddr": "192.168.1.255",
			"name": "br-lan"
		},
		{
			"netmask": "255.255.255.0",
			"data": [
				
			],
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": "10.1.1.1",
			"prefix": 24,
			"family": "inet",
			"dstaddr": "10.1.1.255",
			"broadaddr": "10.1.1.255",
			"name": "eth0.2"
		},
		{
			"flags": {
				"broadcast": false,
				"promisc": false,
				"up": true,
				"loopback": true,
				"noarp": false,
				"multicast": false,
				"pointtopoint": false
			},
			"addr": "::1",
			"name": "lo",
			"family": "inet6",
			"prefix": 128,
			"data": [
				
			],
			"netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
		},
		{
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": ""Removed"",
			"name": "eth0",
			"family": "inet6",
			"prefix": 64,
			"data": [
				
			],
			"netmask": "ffff:ffff:ffff:ffff::"
		},
		{
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": "2001:2::1",
			"name": "br-lan",
			"family": "inet6",
			"prefix": 64,
			"data": [
				
			],
			"netmask": "ffff:ffff:ffff:ffff::"
		},
		{
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": ""Removed"",
			"name": "br-lan",
			"family": "inet6",
			"prefix": 64,
			"data": [
				
			],
			"netmask": "ffff:ffff:ffff:ffff::"
		},
		{
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": "2001:1::1",
			"name": "eth0.2",
			"family": "inet6",
			"prefix": 64,
			"data": [
				
			],
			"netmask": "ffff:ffff:ffff:ffff::"
		},
		{
			"flags": {
				"broadcast": true,
				"promisc": false,
				"up": true,
				"loopback": false,
				"noarp": false,
				"multicast": true,
				"pointtopoint": false
			},
			"addr": ""Removed"",
			"name": "eth0.2",
			"family": "inet6",
			"prefix": 64,
			"data": [
				
			],
			"netmask": "ffff:ffff:ffff:ffff::"
		}
	]
}
{
	"switch": {
		"switch0": {
			"enable": true,
			"roles": [
				{
					"ports": "1 2 3 4 5t",
					"role": "lan",
					"device": "eth0.1"
				},
				{
					"ports": "0 5t",
					"role": "wan",
					"device": "eth0.2"
				}
			],
			"ports": [
				{
					"role": "lan",
					"num": 1
				},
				{
					"role": "lan",
					"num": 2
				},
				{
					"role": "lan",
					"num": 3
				},
				{
					"role": "lan",
					"num": 4
				},
				{
					"role": "wan",
					"num": 0
				},
				{
					"device": "eth0",
					"num": 5,
					"want_untag": false,
					"need_tag": false
				}
			],
			"reset": true
		}
	},
	"network": {
		"wan": {
			"protocol": "dhcp",
			"ifname": "eth0.2"
		},
		"lan": {
			"protocol": "static",
			"ifname": "eth0.1"
		}
	},
	"model": {
		"id": "tplink,tl-wr1043nd-v1",
		"name": "TP-Link TL-WR1043ND v1"
	}
}
{
	"interface": [
		{
			"interface": "lan",
			"up": true,
			"pending": false,
			"available": true,
			"autostart": true,
			"dynamic": false,
			"uptime": 194,
			"l3_device": "br-lan",
			"proto": "static",
			"device": "br-lan",
			"updated": [
				"addresses",
				"routes"
			],
			"metric": 0,
			"dns_metric": 0,
			"delegation": true,
			"ipv4-address": [
				{
					"address": "192.168.1.7",
					"mask": 24
				}
			],
			"ipv6-address": [
				{
					"address": "2001:2::1",
					"mask": 64
				}
			],
			"ipv6-prefix": [
				
			],
			"ipv6-prefix-assignment": [
				
			],
			"route": [
				{
					"target": "0.0.0.0",
					"mask": 0,
					"nexthop": "192.168.1.7",
					"source": "0.0.0.0/0"
				}
			],
			"dns-server": [
				
			],
			"dns-search": [
				
			],
			"neighbors": [
				
			],
			"inactive": {
				"ipv4-address": [
					
				],
				"ipv6-address": [
					
				],
				"route": [
					
				],
				"dns-server": [
					
				],
				"dns-search": [
					
				],
				"neighbors": [
					
				]
			},
			"data": {
				
			}
		},
		{
			"interface": "loopback",
			"up": true,
			"pending": false,
			"available": true,
			"autostart": true,
			"dynamic": false,
			"uptime": 194,
			"l3_device": "lo",
			"proto": "static",
			"device": "lo",
			"updated": [
				"addresses"
			],
			"metric": 0,
			"dns_metric": 0,
			"delegation": true,
			"ipv4-address": [
				{
					"address": "127.0.0.1",
					"mask": 8
				}
			],
			"ipv6-address": [
				
			],
			"ipv6-prefix": [
				
			],
			"ipv6-prefix-assignment": [
				
			],
			"route": [
				
			],
			"dns-server": [
				
			],
			"dns-search": [
				
			],
			"neighbors": [
				
			],
			"inactive": {
				"ipv4-address": [
					
				],
				"ipv6-address": [
					
				],
				"route": [
					
				],
				"dns-server": [
					
				],
				"dns-search": [
					
				],
				"neighbors": [
					
				]
			},
			"data": {
				
			}
		},
		{
			"interface": "wan",
			"up": true,
			"pending": false,
			"available": true,
			"autostart": true,
			"dynamic": false,
			"uptime": 194,
			"l3_device": "eth0.2",
			"proto": "static",
			"device": "eth0.2",
			"updated": [
				"addresses",
				"routes"
			],
			"metric": 0,
			"dns_metric": 0,
			"delegation": true,
			"ipv4-address": [
				{
					"address": "10.1.1.1",
					"mask": 24
				}
			],
			"ipv6-address": [
				{
					"address": "2001:1::1",
					"mask": 64
				}
			],
			"ipv6-prefix": [
				
			],
			"ipv6-prefix-assignment": [
				
			],
			"route": [
				{
					"target": "::",
					"mask": 0,
					"nexthop": "2001:1::2",
					"source": "::/0"
				}
			],
			"dns-server": [
				
			],
			"dns-search": [
				
			],
			"neighbors": [
				
			],
			"inactive": {
				"ipv4-address": [
					
				],
				"ipv6-address": [
					
				],
				"route": [
					
				],
				"dns-server": [
					
				],
				"dns-search": [
					
				],
				"neighbors": [
					
				]
			},
			"data": {
				
			}
		},
		{
			"interface": "wan6",
			"up": false,
			"pending": true,
			"available": true,
			"autostart": true,
			"dynamic": false,
			"proto": "dhcpv6",
			"device": "eth0.2",
			"data": {
				
			}
		}
	]
}
{
	"br-lan": {
		"external": false,
		"present": true,
		"type": "bridge",
		"up": true,
		"carrier": true,
		"bridge-members": [
			"eth0.1"
		],
		"mtu": 1500,
		"mtu6": 1500,
		"macaddr": "Removed",
		"txqueuelen": 1000,
		"ipv6": true,
		"promisc": false,
		"rpfilter": 0,
		"acceptlocal": false,
		"igmpversion": 0,
		"mldversion": 0,
		"neigh4reachabletime": 30000,
		"neigh6reachabletime": 30000,
		"neigh4gcstaletime": 60,
		"neigh6gcstaletime": 60,
		"neigh4locktime": 100,
		"dadtransmits": 1,
		"multicast": true,
		"sendredirects": true,
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 0,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 149484,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 1762,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 0,
			"tx_aborted_errors": 0,
			"tx_packets": 1543,
			"rx_errors": 0,
			"tx_bytes": 158028,
			"tx_window_errors": 0,
			"rx_fifo_errors": 0,
			"tx_carrier_errors": 0
		}
	},
	"eth0": {
		"external": false,
		"present": true,
		"type": "Network device",
		"up": true,
		"carrier": true,
		"link-advertising": [
			"1000baseT-H",
			"1000baseT-F"
		],
		"link-partner-advertising": [
			"1000baseT-F"
		],
		"link-supported": [
			"1000baseT-H",
			"1000baseT-F"
		],
		"speed": "1000F",
		"autoneg": true,
		"mtu": 1500,
		"mtu6": 1500,
		"macaddr": "Removed",
		"txqueuelen": 1000,
		"ipv6": true,
		"promisc": false,
		"rpfilter": 0,
		"acceptlocal": false,
		"igmpversion": 0,
		"mldversion": 0,
		"neigh4reachabletime": 30000,
		"neigh6reachabletime": 30000,
		"neigh4gcstaletime": 60,
		"neigh6gcstaletime": 60,
		"neigh4locktime": 100,
		"dadtransmits": 1,
		"multicast": true,
		"sendredirects": true,
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 0,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 207013,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 2003,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 4,
			"tx_aborted_errors": 0,
			"tx_packets": 1663,
			"rx_errors": 0,
			"tx_bytes": 178484,
			"tx_window_errors": 0,
			"rx_fifo_errors": 0,
			"tx_carrier_errors": 0
		}
	},
	"eth0.1": {
		"external": false,
		"present": true,
		"type": "VLAN",
		"up": true,
		"carrier": true,
		"link-advertising": [
			"1000baseT-H",
			"1000baseT-F"
		],
		"link-partner-advertising": [
			"1000baseT-F"
		],
		"link-supported": [
			"1000baseT-H",
			"1000baseT-F"
		],
		"speed": "1000F",
		"autoneg": true,
		"mtu": 1500,
		"mtu6": 1500,
		"macaddr": "Removed",
		"txqueuelen": 1000,
		"ipv6": false,
		"promisc": false,
		"rpfilter": 0,
		"acceptlocal": false,
		"igmpversion": 0,
		"mldversion": 0,
		"neigh4reachabletime": 30000,
		"neigh6reachabletime": 30000,
		"neigh4gcstaletime": 60,
		"neigh6gcstaletime": 60,
		"neigh4locktime": 100,
		"dadtransmits": 1,
		"multicast": true,
		"sendredirects": true,
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 120,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 149668,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 1766,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 4,
			"tx_aborted_errors": 0,
			"tx_packets": 1543,
			"rx_errors": 0,
			"tx_bytes": 158028,
			"tx_window_errors": 0,
			"rx_fifo_errors": 0,
			"tx_carrier_errors": 0
		}
	},
	"eth0.2": {
		"external": false,
		"present": true,
		"type": "VLAN",
		"up": true,
		"carrier": true,
		"link-advertising": [
			"1000baseT-H",
			"1000baseT-F"
		],
		"link-partner-advertising": [
			"1000baseT-F"
		],
		"link-supported": [
			"1000baseT-H",
			"1000baseT-F"
		],
		"speed": "1000F",
		"autoneg": true,
		"mtu": 1500,
		"mtu6": 1500,
		"macaddr": "Removed",
		"txqueuelen": 1000,
		"ipv6": true,
		"promisc": false,
		"rpfilter": 0,
		"acceptlocal": false,
		"igmpversion": 0,
		"mldversion": 0,
		"neigh4reachabletime": 30000,
		"neigh6reachabletime": 30000,
		"neigh4gcstaletime": 60,
		"neigh6gcstaletime": 60,
		"neigh4locktime": 100,
		"dadtransmits": 1,
		"multicast": true,
		"sendredirects": true,
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 18,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 15415,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 156,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 0,
			"tx_aborted_errors": 0,
			"tx_packets": 101,
			"rx_errors": 0,
			"tx_bytes": 12002,
			"tx_window_errors": 0,
			"rx_fifo_errors": 0,
			"tx_carrier_errors": 0
		}
	},
	"lo": {
		"external": false,
		"present": true,
		"type": "Network device",
		"up": true,
		"carrier": true,
		"mtu": 65536,
		"mtu6": 65536,
		"macaddr": "00:00:00:00:00:00",
		"txqueuelen": 1000,
		"ipv6": true,
		"promisc": false,
		"rpfilter": 0,
		"acceptlocal": false,
		"igmpversion": 0,
		"mldversion": 0,
		"neigh4reachabletime": 30000,
		"neigh6reachabletime": 30000,
		"neigh4gcstaletime": 60,
		"neigh6gcstaletime": 60,
		"neigh4locktime": 100,
		"dadtransmits": 1,
		"multicast": false,
		"sendredirects": true,
		"statistics": {
			"collisions": 0,
			"rx_frame_errors": 0,
			"tx_compressed": 0,
			"multicast": 0,
			"rx_length_errors": 0,
			"tx_dropped": 0,
			"rx_bytes": 12128,
			"rx_missed_errors": 0,
			"tx_errors": 0,
			"rx_compressed": 0,
			"rx_over_errors": 0,
			"tx_fifo_errors": 0,
			"rx_crc_errors": 0,
			"rx_packets": 173,
			"tx_heartbeat_errors": 0,
			"rx_dropped": 0,
			"tx_aborted_errors": 0,
			"tx_packets": 173,
			"rx_errors": 0,
			"tx_bytes": 12128,
			"tx_window_errors": 0,
			"rx_fifo_errors": 0,
			"tx_carrier_errors": 0
		}
	}
}
```

**Comment by jow-** [comment]
Thank you for the data - that helped a lot to find the root cause.

**Comment by gwlim** [comment]
Hi @jow-  can I also trouble you to look at this?
https://bugs.openwrt.org/index.php?do=details&task_id=2364&order=dateopened&sort=desc
It is a very serious bug and I tested it using a cleanly build trunk with LuCI
